title: 揭露邪教"新天地"
author: antiscj
email: antiscj@protonmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  本站收集新天地邪教相关活动与信息，揭露其邪教本质，帮助主内小羊防范此异端。
google_analytics: UA-135105640-1
show_excerpts: true
excerpt_separator: <!--more-->
paginate: 6
paginate_path: "/page:num"
markdown: kramdown
theme: minima
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  antiscj
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
